### ISSUE TITLE
Resume training from checkpoint

### ISSUE THREAD

**Issue by Cphyr** [Hannibal046/nanoDPR#6]
Hey, is there a way to resume training from the already saved checkpoints (step-N)? If not, how would someone add this to train_dpr.py?

**Comment by Hannibal046** [comment]
Hi, the `resume training` mechanism is not implemented in the current version because the training process is stable and lasts only 4.5 hours in our setting. If you are interested in implementing this following the instruction [here](https://huggingface.co/docs/accelerate/usage_guides/checkpoint), welcome PR!
